### PR TITLE
Add support for Ruby 2.1

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: These changes originally started out with the intent of adding Ruby 2.1 to the Travis CI build matrix, as well as to the list of supported Ruby versions. However, as changes have occurred over time in the gem dependencies, ActiveSupport and ShouldaMatchers, some additional updates were required to the test helper in order for them to be useable across the various Ruby versions. I've also updated the Rubinius version used in the build matrix to match Travis CI. :sweat_smile:

### CODE REVIEW

**Comment by sferik** [comment]
Overall, this looks okay but there are more commits than there are lines changed. Would you mind squashing some of the intermediate commits? (If you need help with this, please read the section titled [“Interactively rebase local commits before pushing”](http://mislav.uniqpath.com/2013/02/merge-vs-rebase/).) Thanks! :smile_cat:

**Comment by sgerrand** [comment]
> Would you mind squashing some of the intermediate commits?

I'm more than happy to; I'd submitted this initially for feedback.

**Comment by sgerrand** [comment]
@sferik :wave: The commit history for these changes should be more concise now.

**Comment by sferik** [comment]
:+1: Thanks!

**Comment by sgerrand** [comment]
:smiley_cat: :sparkles:

**Pull request merged**
